<a href="https://colab.research.google.com/github/vaishnavi-gujare/Dataframe-projects/blob/main/fifa_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [1]:
from google.colab import files
uploded = files.upload()

Saving fifa_world_cup_2026_player_performance.csv to fifa_world_cup_2026_player_performance.csv

In [3]:
filepath = '/content/fifa_world_cup_2026_player_performance.csv'
df = pd.read_csv(filepath)

In [ ]:
df

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [ ]:
df.tail()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
df.shape

(54600, 75)

In [ ]:
df.columns

Index(['player_id', 'player_name', 'age', 'nationality', 'team',
       'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot',
       'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium',
       'city', 'opponent_team', 'tournament_stage', 'match_result',
       'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists',
       'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa',
       'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy',
       'dribbles_attempted', 'successful_dribbles', 'crosses',
       'successful_crosses', 'tackles', 'interceptions', 'clearances',
       'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries',
       'defensive_actions', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage',
       'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves',
       'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh',
       'accelerations', 'decelerations', 'stamina_score', 'player_rating',
       'performance_score', 'offensive_contribution', 'defensive_contribution',
       'possession_impact', 'pressure_resistance', 'creativity_score',
       'consistency_score', 'clutch_performance_score',
       'total_goals_tournament', 'total_assists_tournament',
       'total_minutes_tournament', 'player_of_match_awards',
       'tournament_rating'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [ ]:
df.describe()

,age,jersey_number,height_cm,weight_kg,market_value_eur,goals_team,goals_opponent,minutes_played,goals,assists,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
count,54600.000000,54600.000000,54600.000000,54600.000000,5.460000e+04,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,...,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000
mean,26.296484,13.500000,181.654341,75.754853,2.008445e+07,1.330476,1.330476,36.199817,0.055385,0.052363,...,2.850165,60.318379,46.135778,63.750396,55.572154,0.643993,0.607601,272.300311,0.030659,3.634046
std,4.067519,7.500069,6.277792,3.951481,2.718866e+07,1.147814,1.147814,36.419755,0.251900,0.239021,...,4.228436,20.234988,22.424337,19.860028,13.661343,1.093781,0.931527,116.806184,0.206520,3.163411
min,17.000000,1.000000,163.000000,65.000000,5.288220e+05,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,15.000000,5.000000,25.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,7.000000,177.000000,73.000000,4.444778e+06,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,43.700000,29.800000,46.500000,46.400000,0.000000,0.000000,184.000000,0.000000,0.000000
50%,26.000000,13.500000,182.000000,76.000000,1.027111e+07,1.000000,1.000000,24.000000,0.000000,0.000000,...,1.100000,57.000000,40.500000,61.100000,55.000000,0.000000,0.000000,268.000000,0.000000,5.400000
75%,29.000000,20.000000,186.000000,78.000000,2.342013e+07,2.000000,2.000000,75.000000,0.000000,0.000000,...,4.000000,75.100000,59.000000,78.900000,63.900000,1.000000,1.000000,359.000000,0.000000,6.400000
max,39.000000,26.000000,200.000000,87.000000,2.000000e+08,7.000000,7.000000,90.000000,4.000000,3.000000,...,37.000000,99.000000,99.000000,99.000000,99.000000,10.000000,8.000000,615.000000,4.000000,9.500000

In [ ]:
df.dtypes

player_id                    object
player_name                  object
age                           int64
nationality                  object
team                         object
                             ...
total_goals_tournament        int64
total_assists_tournament      int64
total_minutes_tournament      int64
player_of_match_awards        int64
tournament_rating           float64
Length: 75, dtype: object

In [ ]:
df.isnull().sum()

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

In [ ]:
df.nunique()

player_id                   1248
player_name                 1245
age                           23
nationality                   48
team                          48
                            ...
total_goals_tournament        11
total_assists_tournament       9
total_minutes_tournament     586
player_of_match_awards         5
tournament_rating             63
Length: 75, dtype: int64

In [ ]:
df.sample(5)

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
26162,P01128,Jean Ondoa,24,Cameroonian,Cameroon,10,Defender,178,74,Right,...,3.0,42.0,34.8,34.0,61.2,0,0,427,0,4.8
6592,P00434,Ruslan Bondarenko,28,Ukrainian,Ukraine,18,Midfielder,183,75,Right,...,3.2,60.2,77.4,78.3,90.0,1,1,196,0,6.4
27250,P01138,Moumi Choupo-Moting,30,Cameroonian,Cameroon,20,Midfielder,172,69,Right,...,21.6,93.1,99.0,75.7,64.1,2,1,399,0,8.0
11683,P01154,Aissa Bennacer,26,Tunisian,Tunisia,10,Defender,186,79,Left,...,2.6,51.7,25.6,45.5,54.8,0,0,178,0,4.5
17082,P01043,Nayef Ziyech,28,Moroccan,Morocco,3,Goalkeeper,189,78,Left,...,3.0,50.1,30.0,34.2,45.5,0,0,501,0,6.3

In [ ]:
df.value_counts()

player_id  player_name       age  nationality    team          jersey_number  position    height_cm  weight_kg  preferred_foot  club_name      market_value_eur  match_id  match_date  stadium                  city          opponent_team  tournament_stage  match_result  goals_team  goals_opponent  minutes_played  goals  assists  shots  shots_on_target  expected_goals_xg  expected_assists_xa  key_passes  successful_passes  total_passes  pass_accuracy  dribbles_attempted  successful_dribbles  crosses  successful_crosses  tackles  interceptions  clearances  blocks  aerial_duels_won  aerial_duels_lost  recoveries  defensive_actions  fouls_committed  fouls_suffered  yellow_cards  red_cards  offsides  saves  save_percentage  punches  clean_sheet  goals_conceded  penalty_saves  distance_covered_km  sprint_distance_km  top_speed_kmh  accelerations  decelerations  stamina_score  player_rating  performance_score  offensive_contribution  defensive_contribution  possession_impact  pressure_resistance  creativity_score  consistency_score  clutch_performance_score  total_goals_tournament  total_assists_tournament  total_minutes_tournament  player_of_match_awards  tournament_rating
P01248     Mothobi Mvala     29   South African  South Africa  26             Forward     183        82         Right           Club Africain  4868899           M01039    2026-06-15  AT&T Stadium             Dallas        Colombia       Final             L             0           3               66              0      0        1      0                0.03               0.0                  0           14                 17            0.86           1                   0                    0        0                   0        1              0           0       0                 1                  1           1                  1                1               0             0          1         0      0.00             0        0            0               0              7.5                  0.9                 27.0           21             13             90.1           6.1            67.5               57.9                    38.0                    1.2                31.3                 36.6              44.9               21.2                      0                       0                         254                       0                       6.7                  1
P00001     Kylian Griezmann  24   French         France        1              Goalkeeper  191        81         Right           PSV Eindhoven  16574124          M00024    2026-07-24  Hard Rock Stadium        Miami         Australia      Group Stage       D             1           1               0               0      0        0      0                0.00               0.0                  0           0                  0             0.72           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              67.8           0.0            2.7                10.6                    90.3                    0.0                71.8                 10.8              66.2               60.2                      0                       0                         348                       0                       0.0                  1
                                                                                                                                                                 M00089    2026-07-02  Mercedes-Benz Stadium    Atlanta       Spain          Group Stage       W             2           1               0               0      0        0      0                0.00               0.0                  0           0                  0             0.70           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              54.5           0.0            4.7                6.5                     78.0                    0.0                67.0                 18.0              68.7               67.2                      0                       0                         78                        0                       0.0                  1
                                                                                                                                                                 M00177    2026-07-12  Hard Rock Stadium        Miami         Canada         Group Stage       W             3           0               0               0      0        0      0                0.00               0.0                  0           0                  0             0.70           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              80.6           0.0            4.1                1.5                     65.7                    0.0                52.0                 28.0              83.6               50.3                      0                       0                         405                       0                       0.0                  1
                                                                                                                                                                 M00189    2026-07-14  Gillette Stadium         Boston        Australia      Group Stage       D             0           0               0               0      0        0      0                0.00               0.0                  0           0                  0             0.67           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              98.5           0.0            0.0                15.5                    89.0                    0.0                71.5                 37.5              68.7               40.2                      0                       0                         426                       0                       0.0                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
                                                                                                                                                                 M00385    2026-06-30  Gillette Stadium         Boston        Sweden         Group Stage       L             1           2               75              0      0        0      0                0.00               0.0                  1           8                  13            0.69           1                   0                    1        0                   0        0              3           0       1                 0                  2           3                  1                0               0             0          0         2      0.83             0        0            2               0              6.8                  0.7                 28.5           17             19             91.0           6.1            61.1               4.9                     70.1                    2.2                38.9                 36.0              59.6               48.1                      0                       0                         245                       0                       5.8                  1
                                                                                                                                                                 M00336    2026-07-03  Lincoln Financial Field  Philadelphia  Croatia        Group Stage       W             2           1               80              0      0        0      0                0.00               0.0                  0           12                 17            0.75           0                   0                    0        0                   0        0              1           0       1                 0                  2           1                  1                0               0             0          0         0      0.00             0        0            1               0              6.9                  0.7                 30.3           16             12             84.9           5.8            55.4               8.8                     74.1                    1.9                44.8                 34.6              60.1               33.2                      0                       0                         166                       0                       5.4                  1
                                                                                                                                                                 M00310    2026-07-15  Hard Rock Stadium        Miami         Scotland       Group Stage       L             0           4               0               0      0        0      0                0.00               0.0                  0           0                  0             0.95           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              89.6           0.0            0.0                10.2                    74.9                    0.0                60.0                 43.1              65.8               57.2                      0                       0                         236                       0                       0.0                  1
                                                                                                                                                                 M00296    2026-07-17  SoFi Stadium             Los Angeles   Scotland       Group Stage       D             1           1               50              0      0        0      0                0.00               0.0                  0           7                  11            0.72           0                   0                    0        0                   0        0              1           0       1                 0                  0           1                  1                0               0             0          0         2      0.91             2        0            0               0              4.4                  0.4                 26.0           15             13             85.3           6.5            61.1               1.0                     91.0                    0.7                61.8                 30.0              71.5               64.4                      0                       0                         283                       0                       6.3                  1
                                                                                                                                                                 M00288    2026-07-10  Arrowhead Stadium        Kansas City   Ghana          Group Stage       D             1           1               0               0      0        0      0                0.00               0.0                  0           0                  0             0.71           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              57.7           0.0            0.0                3.2                     86.5                    0.0                69.8                 35.5              62.3               61.5                      0                       0                         401                       0                       0.0                  1
Name: count, Length: 54600, dtype: int64